services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""
    volumes:
      - ./.docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  consumerxml:
    build:
      context: ./agendador-back-end-master/agendador-back-end-master/ConsumerXml
      dockerfile: Dockerfile
    environment:
  # Prefer RABBITMQ_URL when using CloudAMQP (amqps) e.g. amqps://user:pass@host/vhost
  # RABBITMQ_URL: amqps://<user>:<pass>@<cloudamqp-host>/<vhost>
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "/"
  RABBITMQ_USER: admin
  RABBITMQ_PASSWORD: admin
      RABBITMQ_QUEUE: Modelo55
      RABBITMQ_PREFETCH: "20"
      RabbitMQ__Durable: "true"
      RabbitMQ__Exclusive: "false"
      RabbitMQ__AutoDelete: "false"
      RabbitMQ__DeadLetterExchange: dlx.nfe
      RabbitMQ__DeadLetterRoutingKey: Modelo55.dlq
    depends_on:
      - rabbitmq
      - mongo

  searchapi:
    build:
      context: ./contta-search-api-main/contta-search-api-main
    environment:
      NODE_ENV: production
      PORT: "5001"
      MONGODB_URI: mongodb://mongo:27017/contta
      OIDC_ISSUER: http://keycloak:8080/realms/contta
      OIDC_AUDIENCE: contta-portal
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: contta
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "5001:5001"
    depends_on:
  - mongo
  - keycloak

  excelparser:
    build:
      context: ./contta-excel-parser-main/contta-excel-parser-main
    environment:
      NODE_ENV: production
      PORT: "5002"
      PRODUCTION_URL: http://localhost:3000
      OIDC_ISSUER: http://keycloak:8080/realms/contta
      OIDC_AUDIENCE: contta-portal
    ports:
      - "5002:5002"

  website:
    build:
      context: ./contta-website-main/contta-website-main
    environment:
      NODE_ENV: production
  NEXT_PUBLIC_API_URL: http://localhost:5001
  NEXT_PUBLIC_OIDC_ISSUER: http://localhost:8080/realms/contta
  NEXT_PUBLIC_OIDC_CLIENT_ID: contta-portal
    ports:
      - "3000:3000"
    depends_on:
  - searchapi
  - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --import-realm
    volumes:
      - ./.docker/keycloak:/opt/keycloak/data/import
    ports:
      - "8080:8080"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI

volumes:
  mongo_data: {}
