//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corporate.Contta.Schedule.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corporate.Contta.Schedule.Application.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa já cadastrada..
        /// </summary>
        public static string EmpresaJaCadastrada {
            get {
                return ResourceManager.GetString("EmpresaJaCadastrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa já esta cadastrada para outro Usuário Admin.
        /// </summary>
        public static string EmpresaJaCadastradaAdmin {
            get {
                return ResourceManager.GetString("EmpresaJaCadastradaAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa já cadastrada para outro usuário.
        /// </summary>
        public static string EmpresaJaCadastradaUser {
            get {
                return ResourceManager.GetString("EmpresaJaCadastradaUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa não encontrada..
        /// </summary>
        public static string EmpresaNaoEncontrada {
            get {
                return ResourceManager.GetString("EmpresaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao realizar operação..
        /// </summary>
        public static string ErroAoRealizaOperacao {
            get {
                return ResourceManager.GetString("ErroAoRealizaOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ErroTrazerTabelaImpposto {
            get {
                return ResourceManager.GetString("ErroTrazerTabelaImpposto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso..
        /// </summary>
        public static string OperacaoRealizadaComSucesso {
            get {
                return ResourceManager.GetString("OperacaoRealizadaComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senhas divergentes..
        /// </summary>
        public static string SenhasDivergentes {
            get {
                return ResourceManager.GetString("SenhasDivergentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado..
        /// </summary>
        public static string UsuarioNaoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UsurioNãoEncontrado {
            get {
                return ResourceManager.GetString("UsurioNãoEncontrado", resourceCulture);
            }
        }
    }
}
