//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corporate.Contta.Schedule.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CorpoEmail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CorpoEmail() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corporate.Contta.Schedule.Application.Resources.CorpoEmail", typeof(CorpoEmail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;html&gt;
        ///&lt;body&gt;
        ///&lt;img style=&quot;width:150px; height:100px&quot; src=&quot;https://portal-simples-git-develop-conttaampla.vercel.app/static/media/logoContta.b427a30c.png&quot; alt=&quot;logo&quot; /&gt;
        ///
        ///
        ///&lt;p&gt;Olá, {Usuario},&lt;/p&gt;
        ///&lt;p&gt;Recebemos uma solicitação para restaurar sua senha de acesso em nosso site.&lt;/p&gt;
        ///&lt;p&gt;Ela ocorreu em {Data}.&lt;/p&gt;
        ///&lt;p&gt;Se você reconhece essa ação, clique no botão abaixo para prosseguir:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;{Link}&quot;&gt;REDEFINIR SENHA &lt;/a&gt;&lt;/p&gt;
        ///
        ///&lt;p style=&quot;margin-bottom:0px&quot;&gt;Atenciosamente,&lt;/p&gt;
        ///&lt;p style=&quot;margin-top:0p [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string RedefinirSenha {
            get {
                return ResourceManager.GetString("RedefinirSenha", resourceCulture);
            }
        }
    }
}
