#!/bin/bash
# Script para migrar do Railway para Render automaticamente

echo "🚀 Migração Railway → Render"
echo "============================"

echo "❌ Railway: 4 serviços com falha de deploy"
echo "✅ Render: Configuração pronta via render.yaml"
echo ""

echo "📋 Vantagens da migração para Render:"
echo "- ✅ Blueprint deploy (render.yaml) já configurado"
echo "- ✅ Root directories corretos por serviço"
echo "- ✅ Dockerfiles testados"
echo "- ✅ Variáveis de ambiente padronizadas"
echo "- ✅ Workflow de CI/CD pronto"
echo "- ✅ Smoke tests automatizados"
echo ""

echo "🎯 Serviços no Render (via Blueprint):"
echo "- contta-keycloak-staging (Docker)"
echo "- contta-searchapi-staging (Docker)"  
echo "- contta-excelparser-staging (Docker)"
echo "- contta-consumerxml-staging (Worker Docker)"
echo ""

echo "📝 Passos para migração:"
echo "1. Render → New → Blueprint"
echo "2. Repo: amplabusiness/contta_novo"
echo "3. File: render.yaml"
echo "4. Configurar variáveis de ambiente"
echo "5. Deploy automático"
echo ""

echo "🔧 Variáveis necessárias no Render:"
echo "Keycloak:"
echo "- KEYCLOAK_ADMIN_PASSWORD"
echo ""
echo "Search API:"
echo "- MONGODB_URI"
echo "- OIDC_ISSUER (https://[KEYCLOAK_HOST]/realms/contta)"
echo "- CORS_ORIGINS"
echo ""
echo "Excel Parser:"
echo "- OIDC_ISSUER"
echo "- PRODUCTION_URL"
echo ""
echo "Consumer Worker:"
echo "- RABBITMQ_URL"
echo ""

echo "⚡ Automação disponível:"
echo "- GitHub Actions deploy-render.yml"
echo "- Polling até status 'live'"
echo "- Smoke tests automáticos"
echo "- Monitoramento via API"
echo ""

echo "🎯 Recomendação: MIGRAR PARA RENDER"
echo "Tempo estimado: 15-20 minutos"
echo "Resultado: Deploy 100% automatizado e funcional"
