# MIGRADO PARA RENDER - Railway workflow desabilitado
# Use deploy-render.yml para automação completa

name: "[DISABLED] Deploy Backends to Railway - CONTA DELETADA"

on:
  # RAILWAY ACCOUNT DELETED - WORKFLOW PERMANENTLY DISABLED
  # Use deploy-render.yml for all deployments
  # workflow_dispatch:
  #   inputs:
  #     force_deploy:
  #       description: 'Railway account deleted - use Render instead'
  #       required: true
  #       default: 'disabled'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy Search API
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID_SEARCH }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID_SEARCH }}
        working-directory: contta-search-api-main/contta-search-api-main
        run: |
          railway up --ci

      - name: Deploy Excel Parser
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID_EXCEL }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID_EXCEL }}
        working-directory: contta-excel-parser-main/contta-excel-parser-main
        run: |
          railway up --ci
