name: Deploy ConsumerXml to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'agendador-back-end-master/agendador-back-end-master/ConsumerXml/**'
      - '.github/workflows/deploy-consumerxml.yml'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy ConsumerXml
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID_CONSUMER }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID_CONSUMER }}
        working-directory: agendador-back-end-master/agendador-back-end-master/ConsumerXml
        run: |
          railway up --ci
