name: Deploy Render Blueprint

on:
  push:
    branches:
      - main
    paths:
      - render.yaml
      - scripts/auto-blueprint-deploy.*
  workflow_dispatch:

jobs:
  deploy:
    name: Render Blueprint Deploy
    runs-on: ubuntu-latest
    environment: render_api_token
    concurrency:
      group: render-blueprint-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preflight - check secrets
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
        run: |
          missing=""
          for k in RENDER_API_TOKEN; do
            if [ -z "${!k}" ]; then missing="$missing $k"; fi
          done
          if [ -n "$missing" ]; then
            echo "Missing required secrets:$missing (ensure they are set on Environment: render_api_token)" >&2
            exit 1
          fi

      - name: Install deps (jq, curl)
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Run Blueprint Deploy
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
        run: bash scripts/auto-blueprint-deploy.sh

      - name: Smoke check
        if: always()
        run: |
          searchUrl="https://contta-searchapi-staging.onrender.com/health"
          excelUrl="https://contta-excelparser-staging.onrender.com/health"
          echo "Search API: $searchUrl"
          echo "Excel Parser: $excelUrl"
          curl -fsS "$searchUrl" -m 20 || true
          curl -fsS "$excelUrl" -m 20 || true
