name: Smoke Tests (health endpoints)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [post-deploy]
  workflow_run:
    workflows: ["Deploy Backends to Railway"]
    types:
      - completed

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke checks (conditional)
        env:
          SEARCH_API_URL: ${{ secrets.SMOKE_SEARCH_API_URL }}
          EXCEL_API_URL: ${{ secrets.SMOKE_EXCEL_API_URL }}
          WEBSITE_URL: ${{ secrets.SMOKE_WEBSITE_URL }}
          PORTAL_URL: ${{ secrets.SMOKE_PORTAL_URL }}
        run: |
          set -e
          echo "Starting smoke checks..."
          if [ -n "$SEARCH_API_URL" ]; then
            echo "- Search API: $SEARCH_API_URL/health";
            curl -fsSL "$SEARCH_API_URL/health" | jq . >/dev/null || { echo "Search API FAIL"; exit 1; }
          else
            echo "- Search API: skipped (no URL)";
          fi
          if [ -n "$EXCEL_API_URL" ]; then
            echo "- Excel Parser: $EXCEL_API_URL/health";
            curl -fsSL "$EXCEL_API_URL/health" | jq . >/dev/null || { echo "Excel Parser FAIL"; exit 1; }
          else
            echo "- Excel Parser: skipped (no URL)";
          fi
          if [ -n "$WEBSITE_URL" ]; then
            echo "- Website: $WEBSITE_URL";
            curl -fsSL "$WEBSITE_URL/" >/dev/null || { echo "Website FAIL"; exit 1; }
          else
            echo "- Website: skipped (no URL)";
          fi
          if [ -n "$PORTAL_URL" ]; then
            echo "- Portal: $PORTAL_URL";
            curl -fsSL "$PORTAL_URL/" >/dev/null || { echo "Portal FAIL"; exit 1; }
          else
            echo "- Portal: skipped (no URL)";
          fi
          echo "Smoke checks completed."
