name: Deploy Website (Next.js) to Vercel

on:
  push:
    branches: [ main ]
    paths:
      - 'contta-website-main/contta-website-main/**'
      - '.github/workflows/vercel-website.yml'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contta-website-main/contta-website-main
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel Env
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: jp8v9KHpoxePXa6ejnRidUrb
          VERCEL_PROJECT_ID: prj_AU0ftVr2HaFTzna1k3wQ3Dakuwn3
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel build --token=$VERCEL_TOKEN

      - name: Deploy (Prebuilt)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

      - name: Trigger smoke tests
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'post-deploy',
              client_payload: { source: 'vercel-website' }
            })
